name: Needs More Info Labeler
on:
  issues:
    types: [opened, edited]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'JacksonKearl/vscode-triage-github-actions'
          ref: master # todo: change to tags once stabalized
      - name: Install Actions
        run: npm install --production
      - name: Run Needs More Info Labeler
        uses: ./needs-more-info-labeler
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          matcher: '\b(\d\.\d{2,3}\.\d|insiders?|1\.\d\d\d?)\b'
          label: needs more info
          comment: this needs some more info plz
          bots: vscode-triage-bot
          flag-team: you betcha
